### ISSUE TITLE
ERROR:  stack depth limit exceeded

### ISSUE THREAD

**Issue by mikesmo** [lian/bitcoin-ruby#109]
When running bitcoin_node with postgres as the squeal backend I'm getting the following error:

Then all the blocks become Ophaned..
```
WARN  network: #<Sequel::DatabaseError: PG::StatementTooComplex: ERROR:  stack depth limit exceeded
HINT:  Increase the configuration parameter "max_stack_depth" (currently 2048kB), after ensuring the platform's stack depth limit is adequate.
>
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:161:in `async_exec'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:161:in `block in execute_query'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/database/logging.rb:33:in `log_yield'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:161:in `execute_query'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:148:in `block in execute'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:124:in `check_disconnect_errors'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:148:in `execute'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:492:in `_execute'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:316:in `block (2 levels) in execute'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:513:in `check_database_errors'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:316:in `block in execute'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/database/connecting.rb:250:in `block in synchronize'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/database/connecting.rb:250:in `synchronize'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:316:in `execute'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:906:in `execute'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:636:in `fetch_rows'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:139:in `each'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:389:in `map'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:389:in `map'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/storage/sequel/sequel_store.rb:342:in `get_txins_for_txouts'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:198:in `spent_outs_txins'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:347:in `not_spent'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:250:in `block (2 levels) in validate'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:249:in `each'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:249:in `with_index'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:249:in `block in validate'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:247:in `each'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:247:in `validate'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:172:in `block in transactions_context'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:170:in `each'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:170:in `all?'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:170:in `transactions_context'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:47:in `block (2 levels) in validate'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:46:in `each'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:46:in `with_index'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:46:in `block in validate'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:44:in `each'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/validation.rb:44:in `validate'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/storage/storage.rb:149:in `store_block'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/storage/storage.rb:98:in `new_block'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/network/node.rb:412:in `work_queue'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/eventmachine-1.0.3/lib/em/timers.rb:56:in `call'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/eventmachine-1.0.3/lib/em/timers.rb:56:in `fire'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `call'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
/Users/mike_smo/.rvm/gems/ruby-2.0.0-p195/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
/Users/mike_smo/dev/bitcoin-ruby/lib/bitcoin/network/node.rb:222:in `run'
bitcoin_node:152:in `<main>'
```

**Comment by mhanne** [comment]
Continued in https://github.com/mhanne/bitcoin-ruby-blockchain/issues/5
