### ISSUE TITLE
RuntimeError: Script type must be hash160, pubkey, p2wpkh or multisig

### ISSUE THREAD

**Issue by yegor256** [lian/bitcoin-ruby#287]
How to convert a bitcoin address (starts with `1`) to the right format acceptable by `script`? I'm doing this:

```ruby
      tx.output do |o|
        o.value(satoshi)
        o.script { |s| s.recipient('1GzqkR2zNQUzHLpE7PLPjVNJ51FHC3bpDH') }
      end
```

I'm getting: 

```
RuntimeError: Script type must be hash160, pubkey, p2wpkh or multisig
    /Users/yegor/.rvm/gems/ruby-2.6.0/gems/bitcoin-ruby-0.0.19/lib/bitcoin/builder.rb:239:in `sig_hash_and_all_keys_exist?'
    /Users/yegor/.rvm/gems/ruby-2.6.0/gems/bitcoin-ruby-0.0.19/lib/bitcoin/builder.rb:308:in `sign_input'
    /Users/yegor/.rvm/gems/ruby-2.6.0/gems/bitcoin-ruby-0.0.19/lib/bitcoin/builder.rb:208:in `block in tx'
    /Users/yegor/.rvm/gems/ruby-2.6.0/gems/bitcoin-ruby-0.0.19/lib/bitcoin/builder.rb:207:in `each'
    /Users/yegor/.rvm/gems/ruby-2.6.0/gems/bitcoin-ruby-0.0.19/lib/bitcoin/builder.rb:207:in `each_with_index'
    /Users/yegor/.rvm/gems/ruby-2.6.0/gems/bitcoin-ruby-0.0.19/lib/bitcoin/builder.rb:207:in `tx'
    /Users/yegor/.rvm/gems/ruby-2.6.0/gems/bitcoin-ruby-0.0.19/lib/bitcoin/builder.rb:21:in `build_tx'
```

I suspect there is something wrong with the format of the destination address.

**Comment by yegor256** [comment]
I guess I know what's wrong. The `tx['script']` is not a text, but a hash. That's why it can't be parsed. How do I conver hash160 script into its text format?

**Comment by pierrenoizat** [comment]
Sorry for necroposting but your prev_out in the tx.input block cannot be the new tx instance: it must be the tx id of the utxo being spent, in hex format.
