### ISSUE TITLE
Incompatible Character Encodings with mysql2 gem

### ISSUE THREAD

**Issue by Hammit** [lian/bitcoin-ruby#54]
I'm trying to import BitcoinD block files.

*Create DB with any of the following*
```
mysqladmin -u root create bitcoin_ruby
mysqladmin -u root --default-character-set=utf8 create bitcoin_ruby
mysqladmin -u root --default-character-set=ascii create bitcoin_ruby
```

*This is the snippet of output for the FATAL network error I'm getting...*

```
ruby -Ilib bin/bitcoin_node --import ~/.bitcoin/blocks/ --skip-validation
 INFO storage: opened sequel store mysql2://root@localhost/bitcoin_ruby
 INFO storage: Importing /home/byron/.bitcoin/blocks/blk00000.dat
 INFO network: Initialized 176 addrs from $HOME/.bitcoin-ruby/bitcoin/peers.json.
 INFO network: Using Linux epoll
 INFO network: EPOLL: Available file descriptors: 1024
 INFO network: Command socket listening on 127.0.0.1:9999
 INFO network: Server socket listening on 0.0.0.0:8333
 INFO network: Querying addresses from DNS seed: dnsseed.bitcoin.dashjr.org
FATAL network: incompatible character encodings: ASCII-8BIT and UTF-8
$USER/git/bitcoin-ruby/lib/bitcoin/protocol/txin.rb:66:in `to_payload'
$USER/git/bitcoin-ruby/lib/bitcoin/protocol/tx.rb:93:in `block in to_payload'
$USER/git/bitcoin-ruby/lib/bitcoin/protocol/tx.rb:93:in `each'
$USER/git/bitcoin-ruby/lib/bitcoin/protocol/tx.rb:93:in `to_payload'
$USER/git/bitcoin-ruby/lib/bitcoin/storage/sequel/sequel_store.rb:384:in `wrap_tx'
$USER/git/bitcoin-ruby/lib/bitcoin/storage/sequel/sequel_store.rb:361:in `block in wrap_block'
```

**Comment by mhanne** [comment]
Continued in https://github.com/mhanne/bitcoin-ruby-blockchain/issues/10
